cursor            #d1c973
cursor_text_color #353100

foreground            #e7e2d5
background            #0f0e07
selection_foreground  #333117
selection_background  #ccc8a3
url_color             #ccc8a3

#: black 000000 767676
color0  #14140c
color8  #36352c
#: red cc0403 f2201f
color1  #000000
color9  #601714
#: green 19cb00 23fd00
color2  #ccc8a3
color10 #e9e4be
#: yellow cecb00 fffd00
color3  #a5d0ba
color11 #c1ecd5
#: blue 0d73cc 1a8fff
color4  #4d4800
color12 #d1c973
#: magenta cb1ed1 fd28ff
color5  #4a482c
color13 #ccc8a3
#: cyan 0dcdcd 14ffff
color6  #274e3d
color14 #a5d0ba
#: white dddddd ffffff
color7  #cbc7b5
color15 #e7e2d5

mark1_foreground #1e1c00
mark1_background #ede68c
mark2_foreground #1e1c05
mark2_background #e9e4be
mark3_foreground #002115
mark3_background #c1ecd5

active_tab_foreground #353100
active_tab_background #d1c973
inactive_tab_foreground #ede68c
inactive_tab_background #4d4800

active_border_color #d1c973
inactive_border_color #353100
# bell_border_color #ff5a00