# --- Main Colors ---
background            #040209
foreground            #e6e1e9
cursor                #e6e1e9
cursor_text_color     #141318

selection_background  #494458
selection_foreground  #e7dff8

url_color             #eeb8ca

# --- ANSI Colors ---
color0                #141318
color1                #ffb4ab
color2                #eeb8ca
color3                #cbc3dc
color4                #cdbdff
color5                #eeb8ca
color6                #cbc3dc
color7                #e6e1e9

color8                #48454e
color9                #93000a
color10               #633b4a
color11               #494458
color12               #4b3e76
color13               #494458
color14               #633b4a
color15               #cac4cf

# --- Starship Prompt Bubbles ---
color255              #4b3e76
color254              #cdbdff
color253              #494458
color252              #cbc3dc
color251              #633b4a
color250              #eeb8ca
color249              #93000a
color248              #ffb4ab

color232              #e7deff
color233              #34275e
color234              #e7dff8
color235              #322e41
color236              #ffd9e4
color237              #492533
color238              #ffdad6
color239              #690005
color240              #e7deff

# Matched with unthemed light/dark
color243              #cdbdff
color244              #ffb4ab
color245              #48454e

# --- UI Elements ---
active_tab_foreground   #34275e
active_tab_background   #cdbdff
inactive_tab_foreground #e7deff
inactive_tab_background #4b3e76

active_border_color     #cdbdff
inactive_border_color   #938f99

# --- Marks ---
mark1_foreground        #1f1048
mark1_background        #e7deff
mark2_foreground        #1d192b
mark2_background        #e7dff8
mark3_foreground        #31111e
mark3_background        #ffd9e4
