# Auto Confirm to Quit
confirm_os_window_close 0

# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# shell
shell /bin/fish

# Transparency
background_opacity 0.90

# Cursor
cursor_shape beam
cursor_blink_interval 0

# Padding
window_padding_width 0 8

# Misc
scrollback_lines 5000
enable_audio_bell no


# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME
