# Auto Confirm to Quit
confirm_os_window_close 0

# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0

# shell
shell /bin/fish

# Transparency
background_opacity 0.85

# Dark theme (Tokyo Night)
foreground              #c0caf5
background              #1a1b26
selection_foreground    #c0caf5
selection_background    #283457

color0  #15161e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7aa2f7
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5

# Cursor
cursor_shape beam
cursor_blink_interval 0

# Padding
window_padding_width 0 8

# Misc
scrollback_lines 5000
enable_audio_bell no
